### ISSUE TITLE
Can we host the libraries ourselves?

### ISSUE THREAD

**Issue by AbelLykens** [MeshedPotato/meshedpotato.github.io#4]
A page load requests scripts and assets from bootstrap cdn, cloudflare, google and fontawesome. 

Can we host these locally (if we need them even ;) ).

Looks like a good start to me :)

**Comment by AbelLykens** [comment]
Will look at this ;)

**Comment by brmdbr** [comment]
We can but its a performance tradeoff

**Comment by AbelLykens** [comment]
I like privacy and decentralization ;)

**Comment by tacticalpidgeon** [comment]
this is resolved in #7

**Comment by AbelLykens** [comment]
Fix works :)
